spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.application.name=${NM_APP:api}
spring.datasource.url=jdbc:mysql://${DB_HOST:localhost}:${DB_PORTA:3306}/${DB_NAME:vollmed_api}
spring.datasource.username=${DB_USER:root}
spring.datasource.password=${DB_PASSWORD:ricom0792@}
spring.flyway.locations=db/migration

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.error.include-stacktrace=never

api.security.token.secret=${JWT_SECRET:12345678}